### PR TITLE
Update to LLVM 14 (C++17 support)

### PR DESCRIPTION
**Pull request by andreittr**
Update lib-compiler-rt to 14.0.6.
This is part of a patch set consisting of:
 - [libcxx](https://github.com/unikraft/lib-libcxx/pull/28)
 - [libcxxabi](https://github.com/unikraft/lib-libcxxabi/pull/4)
 - [lib-compiler-rt](https://github.com/unikraft/lib-compiler-rt/pull/12)
 - [libunwind](https://github.com/unikraft/lib-libunwind/pull/7)
 - [musl](https://github.com/unikraft/lib-musl/pull/45)
 - [unikraft/build](https://github.com/unikraft/unikraft/pull/881)

Tested with GCC 11, 12 & 13, and clang 16.

edit: add compiler-specific warnings from @mschlumpp

### CODE REVIEW

**Review by eduardvintila — CHANGES_REQUESTED** [review]
Hey, @andreittr.

Why did you remove this [patch](https://github.com/unikraft/lib-compiler-rt/blob/staging/patches/0001-Modify-atomic.c-to-build-with-GCC.patch)? It's necessary to properly build any application which uses atomics with GCC, since the compiler builtins in GCC differ from those in Clang (for example, `__c11_atomic_store` from Clang has the `__atomic_store_n` counterpart in GCC). Without the patch, one gets `undefined reference` errors on GCC:

```
/usr/bin/ld: /home/X/unikraft/workdir/apps/app-helloworld-cpp-atomic/build/libcompiler_rt.o: in function `lock':
/home/X/unikraft/workdir/apps/app-helloworld-cpp-atomic/build/libcompiler_rt/origin/compiler-rt-14.0.6.src/lib/builtins/atomic.c:104: undefined reference to `__c11_atomic_compare_exchange_weak'
/usr/bin/ld: /home/X/unikraft/workdir/apps/app-helloworld-cpp-atomic/build/libcompiler_rt.o: in function `unlock':
/home/X/unikraft/workdir/apps/app-helloworld-cpp-atomic/build/libcompiler_rt/origin/compiler-rt-14.0.6.src/lib/builtins/atomic.c:98: undefined reference to `__c11_atomic_store'
/usr/bin/ld: /home/X/unikraft/workdir/apps/app-helloworld-cpp-atomic/build/libcompiler_rt.o: in function `__atomic_load_c':
/home/X/unikraft/workdir/apps/app-helloworld-cpp-atomic/build/libcompiler_rt/origin/compiler-rt-14.0.6.src/lib/builtins/atomic.c:180: undefined reference to `__c11_atomic_load'
```

Also, in order to work with version 14.0.6 of `compiler-rt`, the patch probably needs to be updated, since the line numbers/layout of the `atomic.c` source file most likely changed since version 7.

Apart from this, the PR looks good from my POV!

**Comment by andreittr** [comment]
> Why did you remove this [patch](https://github.com/unikraft/lib-compiler-rt/blob/staging/patches/0001-Modify-atomic.c-to-build-with-GCC.patch)?

Whoops; you're completely right, going to bring it back after some adaptation & testing.

edit: reimplemented the old functionality somewhat cleaner, check the new commit.

**Review by StefanJum — APPROVED** [review]
All good, thanks. Needs [unikraft/913](https://github.com/unikraft/unikraft/pull/913) to be integrated for it to work on `arm64` + `clang`.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
Looks good to me. Thanks @andreittr for the great work!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by eduardvintila — COMMENTED** [review]
Looks really good now, thanks @andreittr! 

One more tiny nitpick though... I would remove this first paragraph from the description of the last commit, namely: `Commit https://github.comd53cbf mistakenly removed the
patch that adapts atomic.c to use GCC builtins instead of clang.`.  I find that the removal was necessary and your new implementation is simply better and cleaner - so no need  to mention the "mistakenly removed" part.

It's up to you, of course, if you want to remove this paragraph. We can merge just fine as it is.

**Comment by andreittr** [comment]
> I find that the removal was necessary and your new implementation is simply better and cleaner - so no need to mention the "mistakenly removed" part.

I see your point, removing that patch (if replaced by a cleaner impl) was the right thing to do, however removing the _functionality_ of said patch was the mistake. I'll update the commit message to better make this clear.

edit: @eduardvintila done.

**Review by razvand — APPROVED** [review]
I tested this as well, and it works as expected. Thanks, @andreittr.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

**Review by eduardvintila — APPROVED** [review]
Thanks, everyone!

Approved-by: Eduard Vintilă <eduard.vintila47@gmail.com>
